####需要下载ansible插件 https://plugins.jetbrains.com/plugin/7792-yaml-ansible-support

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/